name: Continuous Integration

on:
  pull_request:
    branches:
      - develop
      - alpha
      - main

jobs:
  test:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@master

      - name: Install node modules
        run: |
          npm install
      - name: Run lint
        run: |
          npm run lint
      - name: Run test
        run: |
          npm run test
      - name: Run build
        run: |
          npm run build